package SistemasGestionEmpresarial;

import static _Main_.Principal.tipo_test;

/**
 *
 * @author Juan José Estévez González
 */
public class Test_Rep_II_Sis_Ges_Emp {
    
    public static void test_Repaso() {
        
                        _Main_.Principal.setAsignatura("SISTEMAS DE GESTIÓN EMPRESARIAL"); //         
                        _Main_.Principal.setTema("REPASO II");
                        
           /*001*/      tipo_test("Los productos que se venden en el punto de venta ...", "Pueden ser cargados de forma masiva desde un fichero.", "No pueden ser cargados de forma masiva desde un fichero.", "Pueden ser cargados de forma masiva desde un fichero, pero solo de los que tengamos stock.", "Pueden ser cargados de forma masiva desde un fichero, pero solo los que haya fabricado\n    nuestra empresa.", "1");
           /*002*/      tipo_test("La Indentación es ...", "Innecesaria en Python\n    y consiste en un desfase de una o varias líneas de código hacia la derecha.", "Imprescindible en Python\n    y consiste en un desfase de una o varias líneas de código hacia la derecha.", "Innecesaria en Python\n    y consiste en introducir líneas en blanco entre diferentes instrucciones.", "Imprescindible en Python\n    y consiste en introducir líneas en blanco entre diferentes instrucciones.", "2");
           /*003*/      tipo_test("Una forma de ver qué modelo usa un formulario es ...", "Pulsando en el 'insecto' y en 'obtener campos de vista'.", "Pulsando en el 'insecto' y en 'comenzar recorrido'.", "Pulsando en el 'insecto' y en 'abrir vista'.", "Ninguna respuesta es correcta.", "4");
           /*004*/      tipo_test("El sistema gestor de base de datos que usa Odoo es ...", "MySQL.", "PostgreSQL.", "SQL Server.", "MongoDB.", "2");
           /*005*/      tipo_test("Al crear un repositorio nuevo para incluir todos los módulos personalizados ...", "Es recomendable agregar la ruta del nuevo repositorio al addons_path del fichero de\n    configuración 'odoo.conf'.", "Se debe agregar la ruta del nuevo repositorio al fichero manifest.", "Se debe agregar la ruta del nuevo repositorio al addons_path del fichero de\n    configuración 'odoo.conf'.", "Es recomendable agregar la ruta del nuevo repositorio al fichero manifest.", "3");
           /*006*/      tipo_test("El módulo de PdV, ¿requiere tener instalados otros módulos?", "Requiere tener instalado Sito web y Chat en vivo.", "Requiere tener instalados Contabilidad e Inventario.", "Requiere tener instalado Marketing y Encuestas", "No, ninguno.", "2");
           /*007*/      tipo_test("Al actualizar Odoo con el instalador descargable desde la página oficial de Odoo ...", "Se actualiza Odoo y su base de datos.", "Se actualiza Odoo, su base de datos y el servidor.", "Se actualiza solo Odoo.", "Ninguna respuesta es correcta.", "3");
           /*008*/      tipo_test("Odoo utiliza una arquitectura ...", "Cliente/servidor en la que los servidores son navegadores web que acceden al cliente\n    Odoo a través de RPC.", "En capas en la que los clientes son navegadores web que acceden al servidor Odoo\n    a través de RPC.", "Cliente/servidor en la que los clientes son navegadores web que acceden al servidor\n    Odoo a través de RPC.", "En capas en la que los servidores son navegadores web que acceden al cliente Odoo\n    a través de RPC.", "3");
           /*009*/      tipo_test("¿Qué beneficios nos aporta actualizar Odoo?", "Últimas funcionalidades.", "Corrección de seguridad o errores.", "Mejoras de funcionamiento.", "Todas las respuestas son correctas.", "4");
           /*010*/      tipo_test("¿Quién fue el creador de Python y a que se debe su nombre?", "Fue creado por Guido Van Rossum y su nombre se debe a la serpiente pitón.", "Fue creado por Guido Van Rossum y su nombre se debe a los Monty Python, un grupo\n    británico de humoristas.", "Fue creado por Steve Jobs y su nombre se debe a la serpiente pitón.", "Fue creado por Steve Jobs y su nombre se debe a los Monty Python, un grupo británico\n    de humoristas.", "2");
           
           /*011*/      tipo_test("Para poder vender un producto en un punto de ventas ...", "Éste debe tener marcado el flag de \"disponible en PdV\".", "Éste debe tener marcado el flag de \"disponible en TPV\".", "Éste debe tener marcado el flag de \"disponible en ITV\".", "Ninguna respuesta es correcta.", "1");
           /*012*/      tipo_test("La sentencia IF ...", "No puede contener en su interior otra sentencia IF.", "Si no se cumple la condición del IF,\n    comprueba si se cumple la condición del ELIF y sino realiza el ELSE.", "Si se cumple la condición del IF,\n    comprueba si se cumple la condición del ELIF y sino realiza el ELSE.", "Ninguna respuesta es correcta.", "2");
           /*013*/      tipo_test("Para agregar un campo a la vista desde Odoo ...", "Pulsaremos en el 'insecto' y en 'obtener campos de vista'.", "Pulsaremos en el 'insecto' y en 'editar vista: formulario'.", "Pulsaremos en el 'insecto' y en 'abrir vista'.", "Ninguna respuesta es correcta.", "2");
           /*014*/      tipo_test("En el archivo odoo.conf, entre otros datos, podemos encontrar ...", "El usuario de la base de datos.", "La contraseña de la base de datos.", "El puerto al que se conecta la base de datos.", "Todas las respuestas son correctas.", "4");
           /*015*/      tipo_test("El comando scaffold ...", "Facilita la creación de un nuevo módulo y su uso es obligatorio en esos casos.", "Facilita la creación de un nuevo modelo y su uso no es obligatorio en esos casos.", "Facilita la creación de un nuevo módulo y su uso no es obligatorio en esos casos.", "Ninguna respuesta es correcta.", "3");
           /*016*/      tipo_test("¿Viene configurado por defecto el PsV en Odoo?", "Verdadero", "Falso.", " ", " ", "2");
           /*017*/      tipo_test("Odoo se puede actualizar ...", "Con un instalador descargable desde la web oficial de Odoo.", "Con Docker.", "Con Github.", "Todas las respuestas son correctas.", "4");
           /*018*/      tipo_test("Un módulo, requiere tener en su interior al menos ...", "Los archivos '__manifest__.py' e '__init__.py'. ", "El archivo '__manifest__.py'.", "El archivo '__init__.py'.", "Ninguna respuesta es correcta.", "1");
           /*019*/      tipo_test("¿Qué opciones encontramos para personalizar Odoo?", "Solamente podemos realizar pequeñas adptaciones.", "Podemos realizar una personalización adaptada a la empresa.", "Podemos modificar módulos, pero no crearlos.", "Podemos crear informes, pero no modificarlos.", "2");
           /*020*/      tipo_test("Python es un lenguaje de programación ...", "Interpretado, multiparadigma, de alto nivel, de tipado dinámico y fuerte.", "Interpretado, multiparadigma, de bajo nivel, de tipado dinámico y fuerte.", "Interpretado, multiparadigma, de alto nivel, de tipado estático y fuerte.", "Interpretado, multiparadigma, de bajo nivel, de tipado dinámico y debil.", "1");
           
           /*021*/      tipo_test("En Odoo, si tenemos varios PdV con conexión a internet para centralizar las\n        transacciones y perdemos la conexión a internet ...", "No podremos hacer uso del PdV.", "Podremos hacer uso del PdV, almacenándose las transacciones en memoria y\n    sincronizándose una vez que volvamos a tener conexión.", "Podremos hacer uso del PdV, pero tendremos que anotarlas en un documento para luego\n    cargarlas manualmente.", "Ninguna respuesta es correcta.", "2");
           /*022*/      tipo_test("El bucle WHILE ...", "Repite la instrucción un número par de veces.", "No termina hasta que no se encuentra con la instrucción break.", "Requiere del símbolo ':' tras la condición.", "Ninguna respuesta es correcta.", "3");
           /*023*/      tipo_test("La extracción de datos desde el botón 'Exportar' ...", "Puede exportar los datos solo en CSV.", "Puede exportar los datos solo en XLSX.", "Puede exportar los datos en XLSX y CSV.", "Ninguna respuesta es correcta.", "3");
           /*024*/      tipo_test("PgAdmin ...", "Es una aplicación que se usa para gestionar, administrar y desarrollar la base de datos de\n    PostgreSQL.", "Es un módulo de Odoo que se usa para gestionar, administrar y desarrollar la base de\n    datos de PostgreSQL.", "Es un apartado de los ajustes de Odoo, que se habilita al entrar en modo desarrollador y\n    que se usa para gestionar, administrar y desarrollar la base de datos de PostgreSQL.", "Ninguna respuesta es correcta.", "1");
           /*025*/      tipo_test("El campo 'depends' del fichero manifest.py en un módulo ...", "Se informa con los módulos que necesita el nuevo módulo para funcionar,\n    pudiendo tener uno o varios.", "Se informa con los modelos que necesita el nuevo módulo para funcionar,\n    pudiendo tener uno o varios.", "Se informa con los módulos que necesita el nuevo módulo para funcionar,\n    pudiendo estar vacío, tener uno o varios.", "Se informa con los modelos que necesita el nuevo módulo para funcionar,\n    pudiendo estar vacío, tener uno o varios.", "3");
           /*026*/      tipo_test("¿Cómo podemos configurar PdV para imprimir facturas?", "Activando el modo desarrollador.", "Activando los modelos en la estructura de base de datos.", "Activando el checkbox de contabilidad en la configuración.", "No es posible esta configuración.", "3");
           /*027*/      tipo_test("Desde las opciones generales de los ajustes de Odoo podremos ...", "Cambiar el logo de nuestra empresa.", "Cambiar las plantillas de los textos que se envían en el cuerpo del mail.", "Cambiar las plantillas de los documentos pdf que se adjuntan en los mails.", "Todas las respuestas son correctas.", "4");
           /*028*/      tipo_test("El archivo '__manifest__.py' sirve para ...", "Declarar un paquete de Python como un módulo Odoo.", "Especificar metadatos del módulo.", "Mostrar el módulo dentro de la lista de aplicaciones Odoo.", "Todas las respuestas son correctas.", "4");
           /*029*/      tipo_test("Odoo Studio, ¿nos permite una personalización avanzada?", "Verdadero.", "Falso.", " ", " ", "1");
           /*030*/      tipo_test("Python ...", "No es open source.", "No es multiplataforma.", "Es el lenguaje con mayor tasa de crecimiento en los últimos años.", "Ninguna respuesta es correcta.", "3");
           
           /*031*/      tipo_test("En el módulo de Odoo de punto de ventas ...", "No hay modo de controlar el dinero en efectivo de la caja.", "El único modo de controlar el dinero en efectivo de la caja es contándolo antes de la\n    apertura del PdV y después del cierre del mismo y anotándolo en un documento para\n    compararlo al día siguiente.", "Se puede controlar siempre y cuando tengamos un cajón de monedas y billetes que\n    disponga de un contador de efectivo.", "Ninguna respuesta es correcta.", "4");
           /*032*/      tipo_test("El bucle FOR ...", "No termina hasta que no se encuentra con la instrucción break.", "Se usa solo para iterar sobre secuencias (lista, tupla, diccionario, cadena, ...)\n    en el orden en el que aparecen los elementos en la secuencia.", "Se usa solo para iterar sobre secuencias (lista, tupla, diccionario, cadena, ...)\n    en un orden aleatorio.", "Ninguna respuesta es correcta.", "2");
           /*033*/      tipo_test("Los grupos en Odoo ...", "Son módulos asignables a usuarios.", "Son bloques donde encapsular una serie de reglas y permisos para luego ser asignados\n    a usuarios.", "Son un conjunto de usuarios que realizan la misma tarea.", "Ninguna respuesta es correcta.", "2");
           /*034*/      tipo_test("Al realizar un cambio en la base de datos con PgAdmin ...", "Éste no se refleja en Odoo.", "Éste no se refleja en Odoo hasta que no naveguemos a la ventana concreta donde\n    hemos realizado el cambio.", "Éste se refleja en Odoo.", "Ninguna respuesta es correcta.", "3");
           /*035*/      tipo_test("Para que un nuevo módulo aparezca en la lista de aplicaciones de Odoo ...", "Bastará con crearlo, por ejemplo, con PyCharm, informar correctamente el manifest y ya\n    aparecerá en la lista.", "Deberemos crearlo, por ejemplo, con PyCharm, sin necesidad de informar el manifest y\n    actualizar la lista de aplicaciones.", "Deberemos crearlo, por ejemplo, con PyCharm, informar correctamente el manifest\n    y actualizar la lista de aplicaciones.", "Ninguna respuesta es correcta.", "3");
           /*036*/      tipo_test("¿Se puede seguir vendiendo en el PdV aunque se pierda la conexión?", "Verdadero.", "Falso.", " ", " ", "1");
           /*037*/      tipo_test("Odoo Studio ...", "Es Open Source.", "Solo se puede usar en la versión Enterprise.", "Es una aplicación creada por terceros.", "Ninguna respuesta es correcta.", "2");
           /*038*/      tipo_test("Los módulos con los que trabajará nuestro Odoo ...", "Se encuentran en el directorio que se especifique en el 'modules_path' del archivo de\n    configuración de odoo (odoo.conf) y solo puede ser un directorio.", "Se encuentran en el directorio que se especifique en el 'addons_path' del archivo de\n    configuración de odoo (odoo.conf) y pueden ser varios directorios.", "No es necesario especificar donde se encuentra en el archivo de configuración de odoo,\n    simplemente bastará con incluirlos en la carpeta addons.", "No es necesario especificar donde se encuentra en el archivo de configuración de odoo,\n    simplemente bastará con incluirlos en la carpeta modules.", "2");
           /*039*/      tipo_test("¿Qué nos permite el uso de Odoo Studio?", "Personalización de informes.", "Creación de módulos propios.", "Personalización de formularios existentes.", "Todas las respuestas son correctas.", "4");
           /*040*/      tipo_test("La función input() ...", "Lee el valor introducido por pantalla y lo puede almacenar en una variable que será del\n    tipo que el usuario informe, es decir, si informa 23, la variable será de tipo entero.", "Siempre devuelve un tipo range.", "Siempre devuelve un tipo string.", "No es posible hacerle un casting a lo que devuelve.", "3");
           
           /*041*/      tipo_test("Para devolver un producto ...", "Se recomienda hacerlo en el back-end, es decir, mediante una cancelación de la venta en\n    el módulo de venta.", "Se recomienda hacerlo en el front-end, es decir, creando una venta en negativo en el\n    módulo de Punto de venta.", "Se recomienda hacerlo en el back-end, es decir, mediante una cancelación de la venta en\n    el módulo de contabilidad.", "Ninguna respuesta es correcta.", "2");
           /*042*/      tipo_test("En el control de errores de Python ...", "Si existe bloque 'finally', éste siempre se ejecuta al final.", "Si existe bloque 'except', éste siempre se ejecuta al final.", "No es necesario indicar 'try' para capturar el error.", "Ninguna respuesta es correcta.", "1");
           /*043*/      tipo_test("En Odoo ...", "Ya existen una serie de grupos por defecto.", "Un usuario puede tener asignado varios grupos.", "Al instalar un módulo se crean unos grupos por defecto con permisos para dicho módulo.", "Todas las respuestas son correctas.", "4");
           /*044*/      tipo_test("Para ver las tablas en PgAdmin deberemos desplegar la siguiente ruta del árbol:", "servidor / base de datos / schemas / public / tables.", "base de datos / servidor / schemas / public / tables.", "tables / public / schemas / base de datos / Servidor.", "schemas / servidor / base de datos / public / tables.", "1");
           /*045*/      tipo_test("Con la herencia ...", "Modificamos directamente el código de un módulo existente.", "En lugar de modificar un módulo existente, creamos un nuevo módulo para realizar las\n    modificaciones oportunas (agregar o quitar funcionalidad) sobre el original.", "Creamos un módulo copia del original el cuál podemos editar sin necesidad de tocar el original.", "Ninguna respuesta es correcta.", "2");
           /*046*/      tipo_test("El módulo de Fabricación, ¿requiere tener instalados otros módulos?", "Requiere tener instalados Mensajería y Chat en vivo.", "Requiere tener instalados Contabilidad e Inventario.", "No requiere de ningún otro módulo.", "No es recomendable tener instalado Calidad.", "2");
           /*047*/      tipo_test("Desde Odoo Studio se puede ...", "Eliminar un módulo existente.", "Modificar un módulo existente.", "Copiar un módulo existente.", "Todas las respuestas son correctas.", "2");
           /*048*/      tipo_test("Los modelos ...", "Son las tablas de la base de dato de un módulo.", "Son una manera de relacionar el programa con la base de datos.", "Son archivos XML.", "Ninguna respuesta es correcta.", "2");
           /*049*/      tipo_test("¿Podemos instalar Odoo Studio en la versión comunitaria de Odoo?", "Verdadero.", "Falso.", " ", " ", "2");
           /*050*/      tipo_test("El terminal de Python ...", "Tiene dos modos de trabajo: interactivo o mediante ejecución de scripts.", "Solo puede ejecutar scripts.", "Solo funciona en modo interactivo.", "Tiene dos modos de trabajo: interactivo o virtual.", "1");
           
           /*051*/      tipo_test("Para hacer uso del módulo de fabricación ...", "Es necesario tener el módulo de Calidad.", "Es necesario tener el módulo de Inventario.", "Es necesario tener el módulo de Punto de venta.", "Ninguna respuesta es correcta.", "2");
           /*052*/      tipo_test("Python estructura el código de la siguiente manera ...", "Las funciones están incluidas en módulos y éstos a su vez incluidos en paquetes o librerías.", "Los módulos están incluidos en funciones y éstos a su vez incluidos en paquetes o librerías.", "Los paquetes o librerías están incluidas en módulos y éstos a su vez incluidos en funciones.", "Ninguna respuesta es correcta.", "1");
           /*053*/      tipo_test("El tipo de usuario que nos permite gestionarle los permisos es ...", "Usuario interno.", "Portal.", "Público.", "Ninguna respuesta es correcta.", "1");
           /*054*/      tipo_test("En PgAdmin podremos realizar una monitorización en tiempo real del estado del\n        servidor de la base de datos haciendo uso ...", "Del Open Developer Tools.", "Del Query Tool.", "Del dashboard.", "Ninguna respuesta es correcta.", "3");
           /*055*/      tipo_test("Para heredar un modelo ...", "Se deberá crear la clase como en la declaración del objeto original sin informar el\n    atributo _inherit.", "Se deberá crear la clase como en la declaración del objeto original e informar el atributo\n    _inherit con el modelo del que se hereda.", "Se deberá crear la clase como en la declaración del objeto original e informar el atributo\n    _inherit con el modelo actual.", "Ninguna respuesta es correcta.", "2");
           /*056*/      tipo_test("¿Se puede importar productos al PdV?", "Verdadero.", "Falso.", " ", " ", "1");
           /*057*/      tipo_test("Al modificar un informe existente desde Odoo Studio ...", "Se pueden agregar campos nuevos que no apunten a ningún valor de la base de datos.", "Se pueden eliminar campos existentes.", "Se pueden agregar campos nuevos que si apunten a algún valor de la base de datos.", "Todas las respuestas son correctas.", "4");
           /*058*/      tipo_test("Los archivos de datos ...", "Son archivos Python que se almacenan en al base de datos.", "Son archivos XML con elementos <record>, siendo cada elemento <record> un registro\n    de base de datos.", "No pueden tener formato CSV.", "Ninguna respuesta es correcta.", "2");
           /*059*/      tipo_test("¿Qué características tiene Python como lenguaje de programación?", "Interpretado y multiparadigma.", "Compilado y multiparadigma.", "Compilado y de alto nivel.", "Interpretado y de bajo nivel.", "1");
           /*060*/      tipo_test("Pycharm ...", "Es un IDE de Python open source.", "Es un IDE de Python que tiene una versión gratuita y otra de pago.", "Es un lenguaje de programación open source.", "Es un lenguaje de programación que tiene una versión gratuita y otra de pago.", "2");
           
           /*061*/      tipo_test("Para fabricar un producto ...", "Es necesario crear su lista de materiales.", "Es necesario marcar el flag de \"Fabricar\".", "Es necesario tener stock de los materiales necesarios.", "Todas las respuestas son correctas.", "4");
           /*062*/      tipo_test("Si tenemos la cadena cad = 'Esto es una prueba' ¿Qué imprimirá print(cad[-7:-1])?", "'prueb'.", "' prueb'.", "'a prueb'.", "'na prueb'.", "2");
           /*063*/      tipo_test("Los permisos sobre objetos de Odoo que podremos habilitar/deshabilitar son:", "Permiso para leer, escribir, crear y eliminar.", "Permiso para leer y escribir.", "Permiso para crear y eliminar.", "Ninguna respuesta es correcta.", "1");
           /*064*/      tipo_test("Para ver las opciones técnicas y otras ayudas para los desarrolladores en Odoo ...", "Es necesario entrar en el modo funcional.", "Es necesario entrar en el modo técnico.", "Es necesario entrar en el modo programador.", "Ninguna respuesta es correcta.", "4");
           /*065*/      tipo_test("Para heredar una vista ...", "Se deberá informar la etiqueta 'inherit' del XML con el ID externo de la vista de la que\n    queremos heredar.", "Se deberá informar la etiqueta 'inherit_id' del XML con el ID externo de la vista de la que\n    queremos heredar.", "Se deberá informar la etiqueta 'inherit' del XML con el nombre de la vista de la que\n    queremos heredar.", "Ninguna respuesta es correcta.", "2");
           /*066*/      tipo_test("¿Debemos configurar el módulo para procesar operaciones basadas en rutas?", "Verdadero.", "Falso.", " ", " ", "1");
           /*067*/      tipo_test("Desde Odoo Studio ...", "Se puede indicar que un campo aparezca solo si se cumple una condición.", "Se puede indicar que un campo sea invisible.", "Se puede indicar que un campo sea obligatorio.", "Todas las respuestas son correctas.", "4");
           /*068*/      tipo_test("Las vistas en Odoo ...", "Son la forma en la que se representan los registros de los modelos para ser mostradas\n    a los usuarios finales.", "Se especifican en XML.", "Pueden ser Kanban.", "Todas las respuestas son correctas.", "4");
           /*069*/      tipo_test("Una vez instalado Python, ¿de qué formas podemos ejecutarlo?", "Desde el símbolo del sistema.", "Desde la ejecución de scrips.", "Desde un entorno de programación IDE PyCharm.", "Todas las respuestas son correctas.", "4");
           /*070*/      tipo_test("El comando Pip ...", "Es un gestor de paquetes usados para instalar paquetes escritos en Python.", "Se ejecuta dentro del terminal de Python.", "Nos permite abrir Python.", "Ninguna respuesta es correcta.", "1");
           
           /*071*/      tipo_test("Las rutas de producción ...", "Permiten fabricar un producto en una cadena de producción con diferentes equipos y\n    hacer un seguimiento de la fabricación.", "Nos aseguran que siempre habrá stock de materiales para fabricar un producto.", "Permiten enviar los pedidos fabricados a los clientes por diferentes rutas.", "Ninguna respuesta es correcta.", "1");
           /*072*/      tipo_test("Al abrir un fichero con el modo 'w' ...", "Si existe,\n    al escribir en él con write() agrega la información al final.", "Si existe,\n    al escribir en él con write() machaca todo el contenido del fichero con la nueva información.", "El modo 'w' no existe.", "Ninguna respuesta es correcta.", "2");
           /*073*/      tipo_test("Un informe QWeb ...", "Es un archivo Python que contiene una etiqueta report_type = 'qweb-pdf'.", "Es un archivo XML que contiene una etiqueta report_type = 'qweb-pdf'.", "Es un archivo CSV que contiene una etiqueta report_type = 'qweb-pdf'.", "Ninguna respuesta es correcta.", "2");
           /*074*/      tipo_test("Desde la herramienta 'Query Tool' de PgAdmin es posible ...", "Modificar un dato de la base de datos.", "Insertar un dato en la base de datos.", "Visualizar un dato en la base de datos.", "Todas las respuestas son correctas.", "4");
           /*075*/      tipo_test("El log de Odoo ...", "Se informa en el fichero que se encuentra en el parámetro logfile del archivo odoo.conf\n    si este parámetro está informado.", "Se informa en el stdout en PyCharm si el parámetro logfile del archivo odoo.conf no está\n    informado.", "Indicará la información de los logs que se produzcan en Odoo en el nivel que se indique\n    en el parámetro log_handler del archivo odoo.conf.", "Todas las respuestas son correctas.", "4");
           /*076*/      tipo_test("¿Qué características nos permite el módulo de Fabricación?", "Permite comprobar la disponibilidad de materiales.", "Permite configurar centros de producción.", "Permite controlar los costes de producción.", "Todas las respuestas son correctas.", "4");
           /*077*/      tipo_test("Al crear un nuevo módulo con Odoo Studio ...", "Se creará en el panel principal con el resto de los módulos.", "Se le podrá crear formularios.", "Se le podrá crear informes.", "Todas las respuestas son correctas.", "4");
           /*078*/      tipo_test("Los modelos pueden relacionarse entre sí ...", "Con relaciones many2one, one2many y many2many.", "Con relaciones m2o, o2m y m2m.", "Con relaciones ManyToOne, OneToMany y ManyToMany.", "Con relaciones mto, otm y mtm.", "1");
           /*079*/      tipo_test("¿Es pip un sistema de gestión de paquetes para Python?", "Verdadero.", "Falso.", " ", " ", "1");
           /*080*/      tipo_test("Las listas y las tuplas ...", "Son tipos parecidos, solo que las listas son homogéneas y las tuplas pueden ser\n    heterogéneas.", "Son tipos parecidos, solo que el contenido de las tuplas no se puede modificar.", "Las tuplas no existen en Python.", "Ambas son homogeneas.", "2");
           
           /*081*/      tipo_test("Las rutas de producción ...", "No tienen por qué tener centros de producción.", "Deben tener centros de producción.", "Deben tener centros de tareas.", "No tienen por qué tener centros de tareas.", "2");
           /*082*/      tipo_test("Al crear una clase en Python ...", "Es recomendable definir su método __init__().", "Es obligatorio definir su método __init__().", "No se debe definir su método __init__().", "Los criterios elevados de seguridad.", "1");
           /*083*/      tipo_test("Para solventar el error de que no se creen las tablas en PostgreSQL al olvidarnos\n        importar los modelos de Python ...", "Bastará con importar en el fichero __init__.py de la raíz del módulo la carpeta models\n    que contiene todos los modelos.", "Bastará con importar en el fichero __init__.py de la carpeta models los modelos\n    que queremos que se carguen.", "Será necesario importar en el fichero __init__.py de la raíz del módulo la carpeta models\n    que contiene todos los modelos, y en el __init__.py de la carpeta models también se\n    deben importan los modelos que queremos que realmente se carguen.", "Ninguna respuesta es correcta.", "3");
           /*084*/      tipo_test("En Odoo podemos encontrarnos con relaciones entre tablas ...", "Many2one: tipo de campo que almacena una relación de muchos (n) a uno (1).", "One2Many: tipo de campo que almacena una relación de uno (1) a muchos (m).", "Many2many: tipo de campo que almacena una relación de muchos (m) a muchos (n).", "Todas las respuestas son correctas.", "4");
           /*085*/      tipo_test("Los niveles del log_handler pueden ser ...", "critical, error, warning, info, debug, notset.", "error, warning, info, debug, notset.", "critical, error, warning, info, debug.", "Ninguna respuesta es correcta.", "1");
           /*086*/      tipo_test("¿El ERP de Odoo necesita una base de datos para funcionar?", "Verdadero.", "Falso.", " ", " ", "1");
           /*087*/      tipo_test("Al crear una vista Kanban en nuestro nuevo módulo con Odoo Studio ...", "Debemos crear antes una vista de lista.", "Podremos indicarle por qué campo se agrupa de manera predeterminada.", "No será posible agrupar los campos de manera predeterminada.", "Ninguna respuesta es correcta.", "2");
           /*088*/      tipo_test("El motor de informes o reports de Odoo utiliza ...", "Qweb.", "Twitter Bootstrap.", "Wkhtmltopdf.", "Todas las respuestas son correctas.", "4");
           /*089*/      tipo_test("¿Qué tipo de datos numéricos podemos encontrar en Python?", "Int.", "Float.", "Complex.", "Todas las respuestas son correctas.", "4");
           /*090*/      tipo_test("Las variables ...", "Deben empezar por letras o por '_', no por números.", "Solo pueden tener letras, números y los símbolos '_' y '@'.", "Python no es case sensitive.", "Solo pueden tener letras y números.", "1");
           
           /*091*/      tipo_test("Las operaciones ...", "Se realizan en centros de producción y una ruta puede tener varias operaciones.", "Se realizan en centros de tareas y una ruta puede tener varias operaciones.", "Se realizan en centros de producción y una ruta puede tener solo una operación.", "Se realizan en centros de tareas y una ruta puede tener solo una operación.", "1");
           /*092*/      tipo_test("Al crear un método ...", "Siempre debe crearse un parámetro, como primer parámetro, que haga referencia a la\n    instancia actual de la clase que se está llamando.", "No es necesario crear un parámetro que haga referencia a la instancia actual de la clase\n    que se está llamando.", "Siempre debe crearse un parámetro, en cualquier posición del método, que haga\n    referencia a la instancia actual de la clase que se está llamando.", "Ninguna respuesta es correcta.", "1");
           /*093*/      tipo_test("Si al instalar o actualizar un módulo, éste se instala correctamente pero no se\n        visualizan los cambios de una nueva vista que hemos creado que hereda de otra,\n        puede ser debido a ...", "Que nos hayamos olvidado de indicar las dependencias en la sección 'depends'\n    del manifest.", "Que hayamos indicado las dependencias en la sección 'depends' del manifest.", "Que nos hayamos olvidado de agregar en el manifest, en la sección 'data', la vista\n    que hayamos creado nueva.", "Que hayamos agregado en el manifest, en la sección 'data', la vista que hayamos\n    creado nueva.", "3");
           /*094*/      tipo_test("Cuando la base de datos es muy grande, no se recomienda realiza backups con ...", "El propio gestor de bases de datos de la interface que nos proporciona Odoo.", "El comando pg_dump que ofrece PostgreSQL.", "PgAdmin.", "La herramienta de terceros 'Database auto-backup'.", "1");
           /*095*/      tipo_test("PyCharm informa que hay un error sintáctico en el código ...", "Mediante una exclamación roja en la parte superior derecha del editor.", "Subrayando en rojo en la barra de desplazamiento vertical la línea errónea.", "Indicando una explicación del error en la línea roja ubicada en la barra de desplazamiento\n    vertical.", "Todas las respuestas son correctas.", "1");
           /*096*/      tipo_test("¿Qué sistema gestor de base de datos utiliza Odoo?", "Microsoft SQL Server.", "PostgreSQL.", "IBM Db2.", "Oracle.", "2");
           /*097*/      tipo_test("Odoo Studio nos permitirá ...", "Crear informes estadísticos.", "Diseñar plantillas para informes.", "Agregar campos a la lista de vistas.", "Todas las respuestas son correctas.", "4");
           /*098*/      tipo_test("Los campos calculados, al declararlos ...", "Necesitan de un atributo 'calculate' con el nombre del método.", "Necesitan de un atributo 'calculated_field' con el nombre del método.", "Necesitan de un atributo 'compute' con el nombre del método.", "Ninguna respuesta es correcta.", "3");
           /*099*/      tipo_test("¿Existen reglas para declarar las variables en Python?", "Deben empezar por letras o por '_', no por números.", "Siempre deben contener números.", "Debo recordar que Python NO es case sensitive.", "No existen reglas para la declaración de las variables.", "1");
           /*100*/      tipo_test("Las constante ...", "Se declaran usando el prefijo const.", "No existen en Python, simplemente se declarar una variable en mayúsculas para indicar\n    que es una constante.", "Se declaran usando la función const().", "Ninguna respuesta es correcta.", "2");
           
           /*101*/      tipo_test("Los datos que necesita el ERP de Odoo, ¿desde dónde se pueden consultar y modificar?", "Solamente desde Odoo.", "Solamente desde PgAdmin.", "Son datos que no se deben modificar.", "Desde Odoo y PgAdmin.", "4");
           /*102*/      tipo_test("¿Existen constantes como tal en Python.", "Verdadero.", "Falso.", " ", " ", "2");
           /*103*/      tipo_test("¿Son necesarios una serie de archivos concretos para desarrollar un módulo?", "No responde a una estructura determinada.", "Necesita ficheros __manifest__.py y el fichero __ini__.py.", "Todos los ficheros incluidos deben ser ficheros XML.", "No son necesarios ficheros concretos de ningún tipo.", "2");
           /*104*/      tipo_test("¿Cómo podemos realizar copias de seguridad y restauraciones de datos?", "Solamente desde Odoo", "Solamente desde el uso de scripts.", "No se deben realizar copias de seguridad.", "Pueden hacerse de muchas formas.", "4");
           /*105*/      tipo_test("¿Qué retorna la función input() de Python?", "Siempre retorna un número.", "Siempre debo utilizarla con la palabra reservada export.", "La función input() siempre devuelve un String.", "Python no implementa la función input().", "3");
           /*106*/      tipo_test("¿Es importante verificar el fichero manifest para que el módulo aparezca en Odoo?", "Verdadero.", "Falso.", " ", " ", "1");
           /*107*/      tipo_test("¿Se puede utilizar PgAdmin para consultar y modificar datos?", "Verdadero.", "Falso.", " ", " ", "1");
           /*108*/      tipo_test("¿Puedo utilizar la palabra 'and' para combinar sentencias condicionales?", "Verdadero.", "Falso.", " ", " ", "1");
           /*109*/      tipo_test("¿Qué tipo de elementos puede contener un módulo de Odoo?", "Objetos de negocio.", "Vistas de objetos.", "Controladores web.", "Todas las respuestas son correctas.", "4");
           /*110*/      tipo_test("¿Qué ocurre si se modifican los datos utilizando PgAdmin?", "No afectan a los datos mostrados por Odoo.", "No se pueden modificar los datos.", "Los cambios afectan directamente.", "Ninguna es correcta.", "3");
           
           /*111*/      tipo_test("¿Se utilizan llaves {} para agrupar bloques en Python?", "Verdadero.", "Falso.", " ", " ", "2");
           /*112*/      tipo_test("¿Permite Odoo la gestión completa de usuarios y grupos?", "Permite la gestión de usuarios, pero no contempla la gestión de grupos.", "Permite administrar grupos, pero no usuarios.", "Permite gestión de grupos y usuarios.", "Ninguna respuesta es correcta.", "3");
           /*113*/      tipo_test("¿Los objetos de negocio vienen representados por clases Python?", "Verdadero.", "Falso.", "No existen los objetos de negocio dentro de los módulos.", "Solamente podemos incluir nuevas vistas.", "1");
           /*114*/      tipo_test("Las posibles adaptaciones a la empresa que se pueden realizar en Odoo:", "Pequeñas adaptaciones modificando logotipo, plantillas de documentos.", "Adaptando formularios e informes según la necesidad de la empresa.", "Creando módulos propios además de poder modificar los ya existentes.", "Todas las respuestas son correctas.", "4");
           /*115*/      tipo_test("Odoo necesita de un sistema de base de datos PostgreSQL para funcionar, además ...", "Al instalar Odoo con el instalador en Windows nos obliga a tener que instalar\n    PostgreSQL separadamente.", "Los datos modificados mediante PgAdmin en PostgreSQL no afectarán a Odoo.", "La administración de los datos guardados en PostgreSQL solo puede gestionarse desde\n    la propia aplicación de Odoo.", "Podemos usar PgAdmin como aplicación de gestión para administración\n    y desarrollado en PostgreSQL.", "4");
           /*116*/      tipo_test("¿Qué nos permite la función range?", "Formatea la presentación de datos por consola.", "Es útil para iterar por bucles for.", "Permite recoger los datos que el usuario pone en consola.", "No existe la implementación de esa función en Python.", "2");
           /*117*/      tipo_test("¿Se pueden definir datos en los ficheros para que sean almacenados en BBDD?", "No es posible, debemos realizarlo desde la aplicación.", "No es posible, debemos realizarlo desde PgAdmin.", "Podemos definir datos que serán almacenados en BBDD.", "Es poco recomendable el uso de estos métodos.", "3");
           /*118*/      tipo_test("¿Establece Odoo diferencias entre los tipos de usuarios?", "Los usuarios 'Público' y 'Portal' tienen reglas preestablecidas.", "No existe tipos de usuarios en Odoo.", "Los usuarios internos son exactamente iguales de 'Portal' y 'Público'.", "Odoo no permite la gestión de permisos de los usuarios.", "1");
           /*119*/      tipo_test("Python es un lenguaje de programación:", "Interpretado.", "Multiparadigma.", "De alto nivel.", "Todas las respuestas son correctas.", "4");
           /*120*/      tipo_test("Dentro de Odoo, la estructura interna de los módulos pueden tener:", "Vistas de objetos que son parte del modelo con definidos en clases Java.", "Ficheros de datos como pueden ser hojas de estilo en cascada y JavaScript.", "Objetos de negocio que están definidos en clases de Python según una sintaxis propia de Odoo.", "Datos estáticos que son archivos CSV que pueden definir vistas y configuraciones.", "3");
           
           /*121*/      tipo_test("¿Permite Python manejar el control de errores con try?", "Python no implementa gestión de errores con bloques try.", "El bloque 'except' se ejecutará siempre.", "El bloque 'finaly' se ejecutará solamente si hay errores.", "El bloque 'finaly' se ejecutará siempre.", "4");
           /*122*/      tipo_test("¿Qué principio es cierto sobre el funcionamiento de Odoo?", "Usa una arquitectura cliente/servidor.", "Se comunica con el servidor usando XML-RPC.", "Existe una capa ORM entre los objetos Python y PostgreSQL.", "Todas las respuestas son correctas.", "4");
           /*123*/      tipo_test("¿Qué tipo de ficheros maneja el motor de informes QWeb?", "HTML.", "CSS.", "*.JAVA.", "XML.", "4");
           /*124*/      tipo_test("En el módulo de Fabricación de Odoo:", "No requiere tener instalados otros módulos como Contabilidad e Inventario.", "Debemos asegurarnos de configurar correctamente el módulo para poder procesar operaciones\n    basadas en rutas de producción.", "Es recomendable contar con el módulo Calidad de la versión Comunitaria.", "Solamente está disponible en la versión Enterprise.", "2");
           /*125*/      tipo_test("A la hora de decidir usar Python podemos tener en cuenta:", "Que dispone de un gran abanico de librerías de terceros para abarcar problemas de\n    Big Data, Data Science, scraping, etc.", "Que es un lenguaje que plantea problemas para interaccionar con otros lenguajes y base de datos.", "Que es un lenguaje para Windows y de código propietario.", "Que no ha tenido una gran tasa de crecimiento  ni aceptación en los últimos años.", "1");
           /*126*/      tipo_test("¿Con qué sentencias cuenta Python para el control de flujo secuencial?", "if.", "if-else.", "if-elif-else.", "Todas las respuestas son correctas.", "4");
           /*127*/      tipo_test("¿Qué representan los controladores?", "Son plantillas HTML que muestran los informes.", "Son capaces de capturar las solicitudes http.", "Son elementos de representación en la vista.", "Ninguna es correcta.", "2");
           /*128*/      tipo_test("¿Cuál suele ser un error comú al desarrollar un módulo?", "Olvidar dependencias en el manifest.", "No arrancar el servidor.", "No arrancar la base de datos.", "No existen problemas en el desarrollo de nuevos módulos.", "1");
           /*129*/      tipo_test("La indentación en Python:", "Complica la comprensión de la lectura del código.", "No supone un elemento importante a tener en cuenta cuando se programa en Python.", "Ayuda a recordar el cierre de llaves para cerrar los bloques de código.", "Se utiliza para agrupar sentencias y poder diferenciar bloques.", "4");
           /*130*/      tipo_test("Para el control de errores en Python:", "Se utiliza 'except' como bloque que contiene el código en el que se maneja el error.", "Se utiliza 'try' como bloque que contiene el código en el que se maneja el error.", "Se utiliza 'except' para indicar que en ese bloque se están capturando los posibles errores.", "Se utiliza 'try' como bloque de código que se ejecutará siempre al final, tanto si hay errores.", "1");
           
           /*131*/      tipo_test("¿Qué lista generaría la función 'range(3)'?", "[0,1,2]", "[1,2,3]", "[0,1,2,3]", "Ninguna es correcta.", "1");
           /*132*/      tipo_test("¿Podemos crear un módulo utilizando herencias?", "Si, aunque solamente heredamos del modelo.", "Si, pudiendo heredar solamente el controlador.", "Si pudiendo afectar a cada componente del MVC.", "No se permite la herencia en la creación de nuevos módulos.", "3");
           /*133*/      tipo_test("¿Permite Odoo agregar campos en formularios desde la propia aplicación?", "Verdadero.", "Falso.", " ", " ", "1");
           /*134*/      tipo_test("La gestión de permisos de usuarios en Odoo:", "Podemos gestionarlos tanto en el momento de crear el usuario, como más adelante.", "No permite que un usuario sea asignado a diferentes compañías.", "A los usuarios tipo 'usuario interno' no se nos permite gestionar sus permisos.", "A los usuarios tipo 'Portal' y 'Publico' si se nos permite gestionar sus permisos.", "1");
           /*135*/      tipo_test("Odoo Studio es un módulo de Odoo:", "Que solo es accesible desde la versión Enterprise, no es OpenSource.", "Que utiliza un lenguaje propio y diferente a XML para representar las vistas.", "Requiere siempre de la realización de scripts de programación,\n    no permite realizar cambios de modo visual.", "Está limitado a la modificación de lo existente sin posibilidad de crear módulos nuevos.", "1");
           /*136*/      tipo_test("¿Permite Python el uso de 'break' y 'continue'?", "Verdadero.", "Falso.", " ", " ", "1");
           /*137*/      tipo_test("¿Es posible configurar el log de Odoo?", "Permite configurar solamente el nivel de error mostrado.", "Permite configurar el nivel de log y el redirigir el destino.", "Siempre se muestra por el 'stdout' y no se puede cambiar.", "Ninguna respuesta es correcta.", "2");
           /*138*/      tipo_test("No deben declararse en el archivo 'manifest' del módulo:", "Se utilizan para configurar los módulos backend no integrados.", "Son clases capaces de capturar las solicitudes http enviadas por cualquier navegador.", "Son controladores externos ya que Odoo no tiene controladores propios.", "Se utilizan para procesar datos en la base de datos sin necesidad del usuario.", "2");
           /*139*/      tipo_test("Los backups y restauraciones de la base de datos en Odoo:", "Pueden hacerse de muchas formas.", "No se pueden automatizar.", "No admiten la creación de scripts para los backups.", "Siempre debemos recurrir a aplicaciones de terceros ya que Odoo no nos proporciona\n    la posibilidad.", "1");
           /*140*/      tipo_test("El fichero de log de Odoo:", "No existe la posibilidad de personalizar la cantidad de salida de la información.", "Por defecto muestra todo el registro de log en el 'stdin'.", "El fichero 'odoo.conf' no contiene los parámetros de configuración de los ficheros de log.", "Puede ser configurado para redirigir los registros de log a otros destinos.", "4");
           
           /*141*/      tipo_test("¿Qué debemos tener en cuenta cuando creamos una clase en Python?", "Debemos utilizar la palabra reservada 'const default'.", "Debemos usar 'class' y de es recomendable definir '__init__()'.", "Debemos usar de manera obligada 'class' y definir '__init__()'.", "Python no permite la creación de clases.", "2");
           /*142*/      tipo_test("El entorno de PyCharm, ¿cómo nos informa de los errores?", "Mediante una exclamación si es un error sintáctico.", "Siempre usando consola, para todos los errores.", "PyCharm no nos indica los errores sintácticos.", "Ninguna de las respuestas es correcta.", "1");
           /*143*/      tipo_test("Para la creación de un módulo con herencias en Odoo:", "La herencia no afecta a los componentes del modelo-vista-controlador.", "Nos permite realizar modificaciones sobre los objetos sin necesidad de realizar\n    las implementaciones sobre ellos.", "Al heredar crea una especie de capa sobre el objeto original pero modificando dicho original.", "Permite la posibilidad de instalarlo pero no se puede desinstalar cuando se requiera.", "2");
           /*144*/      tipo_test("Para poder imprimir facturas a solicitud del cliente\n        y configurar correctamente el punto de venta de la empresa en Odoo:", "Debemos asegurarnos y activar el checkbox de contabilidad en la configuración del módulo PdV.", "Viene configurado por defecto y no es necesario asegurarnos de su configuración.", "No es posible esta configuración dentro del módulo de PdV.", "Debemos editar e informar de la categoría al importar un listado de productos.", "1");
           /*145*/      tipo_test("La administración de usuarios de Odoo:", "Permite la creación de usuarios pero no la gestión de grupos.", "Permite la gestión de grupos pero no eliminar usuarios.", "Permite la creación, gestión de grupos y eliminación de los usuarios.", "Permite la creación y eliminación pero no la gestión de grupos.", "3");
           /*146*/      tipo_test("¿Es 'self' un parámetro que hace referencia a la instancia actual en una clase?", "Verdadero.", "Falso.", " ", " ", "1");
           /*147*/      tipo_test("Con Odoo Studio podemos afirmar que ...", "La inserción de nuevos campos se encuentra limitada a etiquetas de texto y campos.", "Nos permite definir distintos estados en 'pipeline status bar'.", "Permite el diseño de formularios sin posibilidad de incluir imágenes.", "Permite crear informes estadísticos aunque sin vista gráfica.", "2");
           /*148*/      tipo_test("En los bucles while y for en Python:", "No admite la alteración de la secuencia del bucle.", "Se puede usar 'break' para parar la iteración.", "Se puede usar 'break' para parar la iteración siembre que la condición del bucle no sea verdadera.", "Se puede usar 'break' para pasar a la siguiente iteración del bucle.", "2");
           /*149*/      tipo_test("Los archivos de datos cuando se crea un módulo de Odoo:", "Pueden definir datos que se guardarán en la base de datos.", "Están en formato XML con elementos <item> que representan un registro en base de datos.", "Representan datos solamente usados para demostración, no para el funcionamiento del módulo.", "No deben declararse en el archivo 'manifest' del módulo.", "1");
           /*150*/      tipo_test("Referente al sistema de gestión de paquetes 'pip' podemos afirmar que ...", "Al instalar paquetes de terceros limita la potencia de Python.", "Al instalar paquetes de terceros no limita la potencia de Python.", "Se usa para instalar paquetes escritos en Python.", "No puede instalar librerías de terceros, solo paquetes propios de Python.", "3");
           
           /*151*/      tipo_test("Las rutas de producción ...", "No tienen por qué tener centros de producción.", "Deben tener centros de producción.", "Deben tener centros de tareas.", "No tienen por qué tener centros de tareas.", "2");
           /*152*/      //tipo_test("", "", "", "", "", "");
           /*153*/      //tipo_test("", "", "", "", "", "");
           /*154*/      //tipo_test("", "", "", "", "", "");
           /*155*/      //tipo_test("", "", "", "", "", "");
           /*156*/      //tipo_test("", "", "", "", "", "");
           /*157*/      //tipo_test("", "", "", "", "", "");
           /*158*/      //tipo_test("", "", "", "", "", "");
           /*159*/      //tipo_test("", "", "", "", "", "");
           /*160*/      //tipo_test("", "", "", "", "", "");
           
           /*161*/      //tipo_test("", "", "", "", "", "");
           /*162*/      //tipo_test("", "", "", "", "", "");
           /*163*/      //tipo_test("", "", "", "", "", "");
           /*164*/      //tipo_test("", "", "", "", "", "");
           /*165*/      //tipo_test("", "", "", "", "", "");
           /*166*/      //tipo_test("", "", "", "", "", "");
           /*167*/      //tipo_test("", "", "", "", "", "");
           /*168*/      //tipo_test("", "", "", "", "", "");
           /*169*/      //tipo_test("", "", "", "", "", "");
           /*170*/      //tipo_test("", "", "", "", "", "");
           
           /*171*/      //tipo_test("", "", "", "", "", "");
           /*172*/      //tipo_test("", "", "", "", "", "");
           /*173*/      //tipo_test("", "", "", "", "", "");
           /*174*/      //tipo_test("", "", "", "", "", "");
           /*175*/      //tipo_test("", "", "", "", "", "");
           /*176*/      //tipo_test("", "", "", "", "", "");
           /*177*/      //tipo_test("", "", "", "", "", "");
           /*178*/      //tipo_test("", "", "", "", "", "");
           /*179*/      //tipo_test("", "", "", "", "", "");
           /*180*/      //tipo_test("", "", "", "", "", "");
           
           /*181*/      //tipo_test("", "", "", "", "", "");
           /*182*/      //tipo_test("", "", "", "", "", "");
           /*183*/      //tipo_test("", "", "", "", "", "");
           /*184*/      //tipo_test("", "", "", "", "", "");
           /*185*/      //tipo_test("", "", "", "", "", "");
           /*186*/      //tipo_test("", "", "", "", "", "");
           /*187*/      //tipo_test("", "", "", "", "", "");
           /*188*/      //tipo_test("", "", "", "", "", "");
           /*189*/      //tipo_test("", "", "", "", "", "");
           /*190*/      //tipo_test("", "", "", "", "", "");
           
           /*191*/      //tipo_test("", "", "", "", "", "");
           /*192*/      //tipo_test("", "", "", "", "", "");
           /*193*/      //tipo_test("", "", "", "", "", "");
           /*194*/      //tipo_test("", "", "", "", "", "");
           /*195*/      //tipo_test("", "", "", "", "", "");
           /*196*/      //tipo_test("", "", "", "", "", "");
           /*197*/      //tipo_test("", "", "", "", "", "");
           /*198*/      //tipo_test("", "", "", "", "", "");
           /*199*/      //tipo_test("", "", "", "", "", "");
           /*200*/      //tipo_test("", "", "", "", "", "");
           
    }    
}