package DesarrolloInterfaces;

import static _Main_.Principal.tipo_test;

/**
 *
 * @author Juan José Estévez González
 */
public class Test_Rep_II_Des_Int {
    
    public static void test_Repaso() {
        
                        _Main_.Principal.setAsignatura("DESARROLLO DE INTERFACES"); //      uientes elementos permite añadir un conmutador entre estados en 
                        _Main_.Principal.setTema("REPASO II");
                        
           /*001*/      tipo_test("¿Que elemento suelen presentar una acción asociada al ser pulsados?", "Button.", "TextField.", "TextView.", "Spinner.", "1");
           /*002*/      tipo_test("Las pruebas de caja blanca:", "Se basan en la evaluación del código interno del software, un buen diseño para estas\n    pruebas implica la evaluación de todos los posibles caminos que se han implementado\n    en el diseño de un programa.", "Evalúa la aplicación desde un punto de vista externo, es decir, sin preocuparnos del\n    'interior', son las habituales para la prueba de interfaces.", "No permiten validar el funcionamiento del software en base a las especificaciones de diseño.", "Ninguna es correcta.", "1");
           /*003*/      tipo_test("Dentro de las pautas para la creación de una interfaz en iOS, podemos encontrar:", "Claridad, donde se resalta el contenido importante de la aplicación y aporta interactividad.", "Adaptación al contenido, donde la navegación debe realizarse a través de un movimiento fluido.", "Profundidad, relacionada con la sensación de movimiento sobre la jerarquía de capas de la aplicación.", "Todas las respuestas anteriores son correctas.", "4");
           /*004*/      tipo_test("¿Qué fichero de JavaHelp asocia elementos de HTML con un identificador?", "XML.", "JHM.", "HTML.", "Ninguna respuesta es correcta.", "2");
           /*005*/      tipo_test("La parte del fichero de ayuda que se muestra al usuario, habitualmente en forma de\n    índice, glosario, tabla de contenido e incluso buscador de temas es:", "La guía de inicio.", "El mapa de navegación.", "El mapa de fichero.", "La vista de información.", "4");
           /*006*/      tipo_test("Podemos afirmar que ...", "La firma digital permite identificar el firmante de forma inequívoca pero no la integridad\n    del documento firmado.", "La firma en la distribución de software no es un mecanismo para garantizar la autenticidad.", "Se puede realizar una firma digital sobre archivos PDF pero no sobre ficheros Jar.", "La firma digital queda constituida por una clave pública y una clave privada.", "4");
           /*007*/      tipo_test("En la implementación para la detección de eventos, en primer lugar, es necesario\n        implementar el método:", "setOnClickListener.", "ClickListener.", "onClick.", "setOnActivity.", "1");
           /*008*/      tipo_test("¿En qué grupo podemos encontrar elementos que definen la posición del resto?", "Common.", "Buttons.", "Google.", "Layouts.", "4");
           /*009*/      tipo_test("En el manejo de 'Navigation', la propiedad de animación a la transición asociada a la\n        entrada en una pantalla sin una acción emergente, es ...", "app:exitAnim", "app:enterAnim", "app:popEnterAnim", "app:porExitAnim", "2");
           /*010*/      tipo_test("¿Cuál de las siguientes afirmaciones es falsa en cuanto a la confección de informes\n        para aplicaciones?", "Existen dos tipos de informes atendiendo a la forma en la que estos quedan vinculados\n    con la aplicación: incrustados y no incrustado.", "Un informe es un documento que recopila y muestra diferente tipo de información\n    procedente de fuentes de datos a los usuarios, en función de las consultas realizadas.", "La creación de los informes es estática.", "Es posible seleccionar entre múltiples elementos y distribuciones de diseño.", "3");
           
           /*011*/      tipo_test("Las pruebas de integración:", "Del tipo ascendente son las que comienzan realizando la evaluación de los niveles más altos.", "Permiten evaluar el funcionamiento de todos los módulos desarrollados de manera conjunta.", "Del tipo descendente son las que comienzan desde los módulos subordinados hasta el módulo\n    principal.", "No se consideran necesarias para garantizar el correcto funcionamiento de una aplicación.", "2");
           /*012*/      tipo_test("¿Cuál de los siguientes tipos de pruebas de software no es habitual?", "Pruebas unitarias.", "Pruebas de integración.", "Pruebas de inmersión.", "Pruebas de seguridad.", "3");
           /*013*/      tipo_test("Referente a los tipos de documentación y su clasificación podemos encontrar:", "Documentación en función del tipo de aplicación, del tipo de usuario o de la fase concreta.", "Documentación de pruebas con guías y hojas de especificaciones.", "Documenta técnica con los escenarios de prueba y detalles de las mismas.", "Tres grandes grupos: documentación contractual, presupuesto y de contexto.", "1");
           /*014*/      tipo_test("¿Qué tipo de fichero de JavaHelp contiene la distribución del fichero de ayuda?", "XML.", "JHM.", "HTML.", "Ninguna respuesta es correcta.", "1");
           /*015*/      tipo_test("Este tipo de formato de fichero de ayuda actualmente se encuentra en desuso:", "HPJ.", "CHM.", "HLP.", "IPF.", "3");
           /*016*/      tipo_test("En los ficheros de ayuda en formato digital encontramos ...", "Que es posible encontrar un único tipo de formato digital para creación y consulta.", "Suelen estar compuestos por dos partes, mapa de fichero y vista de información.", "La vista de información asocia identificadores a modo de mapa del sistema de ayuda.", "El mapa de fichero muestra al usuario el contenido detallado de cada tema en cuestión.", "2");
           /*017*/      tipo_test("Si el evento que se desea tratar es relativo a hacer click sobre un elemento,\n        necesitaremos utilizar el escuchador:", "OnTouch.", "OnClickTouch.", "OnClickButton.", "OnClickListener.", "4");
           /*018*/      tipo_test("¿En qué grupo podemos encontrar elementos 'extra' como barras de progreso?", "Common.", "Text.", "Widgets.", "Containers.", "3");
           /*019*/      tipo_test("La prueba realizada para evaluar la capacidad de procesamiento del software ante la\n        llegada de una cantidad grande de datos, se denomina ...", "Prueba de volumen.", "Prueba de seguridad.", "Prueba de rendimiento.", "Prueba de Liskov.", "1");
           /*020*/      tipo_test("¿Cuál de las siguientes no es una herramienta gráfica para la creación de informes?", "iReport.", "JasperReport.", "XCode.", "Eclipse Birt.", "3");
           
           /*021*/      tipo_test("En los informes parametrizables que permiten la creación de distintos resultados,\n        encontramos que ...", "Los parámetros 'de usuario' pueden tomar campos, pero no realizar operaciones sobre ellos.", "Los tipos de parámetros 'de usuario' están disponibles desde el entorno de desarrollado\n    y no se pueden crear desde cero.", "Los tipos de parámetros 'integrados' están disponibles de forma predeterminada en el entorno\n    de desarrollo.", "Los parámetros se incluyen con unas propiedades que no se pueden modificar.", "3");
           /*022*/      tipo_test("¿Qué prueba se centra sobre todo en la evaluación de los sistemas de protección y\n        autenticación de una aplicación?", "Pruebas de seguridad.", "Pruebas de integración.", "Pruebas de volumen y carga.", "Pruebas unitarias.", "1");
           /*023*/      tipo_test("Los instaladores realizan todo el proceso necesario para desplegar\n        una aplicación software ...", "Sin comprobar la autenticidad del software o necesidad de librerías.", "Delegando la creación de variables de entorno al usuario administrador.", "Comprobando las especificaciones de software y hardware del equipo.", "Comprimiendo los ficheros del paquete de distribución.", "3");
           /*024*/      tipo_test("¿Qué caracteriza a JavaHelp?", "Ser integrada posteriormente en una aplicación.", "Crear ayudas completas con motores de búsqueda, glosario, etc.", "Está orientada al uso de aplicaciones Java.", "Todas las respuestas son correctas.", "4");
           /*025*/      tipo_test("Este tipo de formato de fichero de ayuda incluía ciertas mejoras sobre HLP:", "CHM.", "HPJ.", "IPF.", "JavaHelp.", "1");
           /*026*/      tipo_test("El componente 'Navigation' dentro del desarrollo de interfaces en Android ...", "Permite implementar cualquier tipo de diseño de navegación a través de la aplicación.", "Permite un escaso grado de personalización respecto al diseño de la interfaz.", "Este componente no se emplea para diseñar secuencia de paso en la navegación.", "Se basa únicamente en dos elementos: 'NavHost' y 'NavController'.", "1");
           /*027*/      tipo_test("El método que se invoca cuando se pulsa sobre un botón físico y el foco está situado\n        sobre un elemento que implementa este método en su escucha es:", "onKey.", "onTouch.", "onLongClick.", "onClick.", "1");
           /*028*/      tipo_test("Android Studio, ¿en qué grupo podemos encontrar componentes habituales como cajas de\n        texto?", "Containers.", "Layouts.", "Widgets.", "Common.", "4");
           /*029*/      tipo_test("En el desarrollo de interfaces en Android el layout denominado LinearLayout ...", "Permite modificar la propiedad de altura con 'layout_height', aunque no la de ancho.", "Permite encontrar el tipo lineal horizontal que realiza la distribución en forma de filas.", "Permite alinear los elementos uno tras otro en una dirección concreta.", "No permite la dimensión de cada uno de los elementos a través de sus propiedades.", "3");
           /*030*/      tipo_test("¿Cuál de las siguientes herramientas modela la encapsulación relativa a la generación\n        de informes?", "Eclipse Pro.", "XCode.", "JasperReport.", "iReport.", "3");
           
           /*031*/      tipo_test("En los sistemas de gestión de paquetes ...", "No se hace necesario incluir todos los componentes de diseño de una aplicación.", "Se consideran como componentes principales las bibliotecas y librerías necesarias.", "Se puede considerar opcional incluir las carpetas de los elementos multimedia usados en el\n    código de la aplicación.", "Los ficheros ejecutables de la aplicación son componentes secundarios.", "2");
           /*032*/      tipo_test("La depuración de código sirve para:", "La revisión del código para la detección de posibles errores y la corrección de los mismos.", "Crear errores de sintaxis.", "Producir fallos de diseño.", "Interpretar las instrucciones correctas.", "1");
           /*033*/      tipo_test("Una tabla de contenido permite reflejar la estructura y contenido del documento,\n        además se caracteriza porque ...", "Se encuentra esquematizada en varios niveles entre los que se distinguen títulos y subtítulos.", "Debe duplicar la información para que esté disponible al usuario en todo momento.", "Se sitúa al final como recordatorio de todo el contenido mostrado.", "Debe mostrar siempre el número de página independientemente diseño.", "1");
           /*034*/      tipo_test("¿Qué tipo de documentación especifica los escenarios de prueba?", "Documentación técnica.", "Documentación de pruebas de entrada.", "Documentación de pruebas de salida.", "Ninguna respuesta es correcta.", "2");
           /*035*/      tipo_test("Este tipo de formato de fichero de ayuda utiliza para la representación de gráficos\n        ficheros de tipo .shg:", "HPJ.", "CHM.", "IPF.", "JavaHelp.", "1");
           /*036*/      tipo_test("Entre los pilares clave para la elección del color en el desarrollo de aplicaciones iOS,\n        encontramos que ...", "Los colores deben funcionar bien de forma independiente, sin necesidad de comprobar si\n    combinan correctamente.", "Debemos usar el color con prudencia.", "Podemos seleccionar una paleta de colores ilimitada sin necesidad de consonancia.", "Proporcionemos siempre un mismo color para el modo oscuro y claro, garantizando así la\n    uniformidad.", "2");
           /*037*/      tipo_test("El método que se debe invocar cuando se mantiene pulsado un elemento de la\n        interfaz es:", "onKey.", "onTouch.", "onLongClick.", "onClick.", "3");
           /*038*/      tipo_test("¿Qué características permite los layout?", "Solo posición y dimensión.", "Solo posición y distribución.", "Solo dimensión y distribución.", "Posición, dimensión y distribución.", "4");
           /*039*/      tipo_test("A la hora de la creación de un informe, los datos de entrada para la creación\n        del informe ...", "Los obtenemos de base de datos relacionales ya que son el único formato soportado para\n    incluir los datos.", "Suponen un elemento importante a tener en cuenta.", "Se deben obtener solamente de un origen de datos de ficheros de intercambio en formato XML.", "No son recomendables incluirlos haciendo uso y aplicación de las plantillas existentes.", "2");
           /*040*/      tipo_test("¿Qué herramienta de código abierto permite la creación de informes de forma\n        dinámica para entornos de inteligencia empresarial?", "JasperReport.", "Eclipse Pro.", "Eclipse Birt.", "iReport.", "3");
           
           /*041*/      tipo_test("Los subinformes son informes incluidos dentro de otros informes ...", "Que permiten obtener varias consultas diferentes en un informe y de forma más organizada.", "Que no tienen características similares, ya que no presentan los datos en base a una plantilla.", "Que tienen existencia por sí mismos ya que existen como objeto independiente y principal.", "Que pueden contener más subinformes, encabezado y pié de página.", "1");
           /*042*/      tipo_test("Las pruebas de integración ascendente:", "Suele tener una integración primero en profundidad y otra integración primero en anchura.", "Se realiza desde el módulo principal hasta los subordinados.", "Comienzan con la evaluación de los niveles más altos.", "Comienzan con la evaluación de los niveles más bajos.", "4");
           /*043*/      tipo_test("Uno de los elementos clave para el desarrollo de interfaces en Android son los layout ...", "Permitiendo definir las características de posición, dimensión y distribución de elementos.", "Permitiendo definir posición y dimensión, pero no permite la distribución de los elementos.", "Permitiendo definir dimensión y distribución, pero no permite la definir la posición\n    de los elementos.", "Los componentes modificarían su tamaño y su posición sin necesidad de layout.", "1");
           /*044*/      tipo_test("¿Qué tipo de documentación corresponde con guías, manuales, hojas de especificaciones,\n        etc?", "Documentación técnica.", "Documentación de pruebas de entrada.", "Documentación de pruebas de salida.", "Ninguna respuesta es correcta.", "1");
           /*045*/      tipo_test("La herramienta Shalom Help Maker:", "Permite la creación de ficheros de ayuda para Windows y tras su descarga es necesario\n    ejecutar el software htmlhelp.exe para instalarla.", "Toda la información queda contenida en un único fichero por lo que es posible exportar\n    toda la ayuda en un solo documento PDF.", "Es una herramienta de pago.", "Permite creación de índices, contenidos enlazados a otras páginas, links externos,\n    así como la creación de imágenes que enriquecen el contenido del documento final.", "4");
           /*046*/      tipo_test("Cuando se incluyen imágenes en un informe, se debe tener en cuenta que ...", "Como elemento visual siempre proporciona un valor añadido.", "Incluir una imagen indicando la ruta absoluta es una opción recomendada solo para pruebas.", "Podemos incluir una imagen indicando una dirección URL.", "Todas las respuestas son correctas.", "4");
           /*047*/      tipo_test("El evento asociado a los elementos 'extra' que permiten personalizar la interfaz de\n        desarrollo (calendarios, barras de progreso, ...) es:", "onKeyListener.", "onClickListener.", "onTouchListener.", "onLongClickListener.", "3");
           /*048*/      tipo_test("¿Qué tipo de componente son componentes contenedores de otros componentes?", "View.", "Text.", "ViewGroup.", "Ninguna respuesta es correcta.", "3");
           /*049*/      tipo_test("Las pruebas son una fase indispensable en el desarrollo de aplicaciones ...", "Ya que permiten validar el funcionamiento del software en base a las especificaciones de diseño.", "Ya que están enfocadas a evaluar el software en un único escenario para todo el diseño.", "Encontrando pruebas de caja blanda, que evalúan la aplicación desde un punto de vista externo.", "Encontrando las pruebas de caja negra que evalúan el código interno del software.", "1");
           /*050*/      tipo_test("¿Qué herramienta de inteligencia empresarial se utiliza para crear informes de forma\n        dinámica sobre todo en el entorno de desarrollo de Microsoft Visual Studio?", "iReport.", "Eclipse Pro.", "Eclipse Birt.", "Crystal Reports.", "4");
           
           /*051*/      tipo_test("Referente a los formatos de salida de un informe:", "Los formatos de ficheros en PDF y CSV no son aconsejables, ni utilizados habitualmente.", "Una ventaja supone la posibilidad de poder adaptar el formato de salida a la finalidad que\n    se le va a dar al informe.", "Se deben exportar solamente a ficheros de intercambio de información en formato XML.", "En el fichero generado, siempre toma importancia los qué datos se muestran,\n    siendo menos importante el cómo se muestran.", "2");
           /*052*/      tipo_test("Las pruebas de regresión:", "Son los errores producidos cuando al realizar la integración de las diferentes partes de un\n    programa se producen errores que de forma individual no ocurrían.", "Sólo se producen cuando la introducción de cambios muestra errores que nada tiene que\n    ver con las modificaciones realizadas.", "Sólo localizan errores que se han producido por la introducción de cambios.", "Es la nueva ejecución de un conjunto de pruebas que ya había sido ejecutado con\n    anterioridad.", "4");
           /*053*/      tipo_test("¿Qué tipo de manual o guía contiene la información necesaria para poner en uso\n        una aplicación?", "El manual de usuario.", "El manual de explotación.", "La guía rápida.", "La guía de referencia.", "2");
           /*054*/      tipo_test("¿Qué tipo de documentación corresponde con los informes resultantes de aplicar pruebas?", "Documentación técnica interna.", "Documentación de pruebas de entrada.", "Documentación de pruebas de salida.", "Documentación técnica externa.", "3");
           /*055*/      tipo_test("Indica cuál de las siguientes afirmaciones es falsa respecto a las tablas de contenidos:", "Las tablas de contenido se sitúan al final de cualquier documento,\n    como si de un índice de libro se tratara.", "Pueden mostrar el número de página o no, en función del diseño.", "Casi siempre incluye un enlace directo en cada uno de los títulos o subtítulos\n    por los que aparece compuesta.", "No debe duplicarse la información.", "1");
           /*056*/      tipo_test("¿Desde que fichero será necesario acceder para que esté disponible la pantalla\n        de diseño y el código asociado a la creación de cada nuevo componente?", "Main_activity.xml", "Activity_proyect.xml", "Activity_main.xml", "Content_main.xml", "3");
           /*057*/      tipo_test("A través de este componente es posible implementar cualquier tipo de diseño de\n        navegación por una aplicación, aportando un alto grado de personalización al diseño\n        de la interfaz:", "Graphics.", "Navigation.", "Illustrate.", "Entertain.", "2");
           /*058*/      tipo_test("¿Qué fichero se muestra por defecto cuando se accede por primera vez al proyecto?", "MainActivity.kt", "ic_launcher_background.xml", "script_grade.js", "Ninguna respuesta es correcta.", "1");
           /*059*/      //tipo_test("", "", "", "", "", "");
           /*060*/      tipo_test("¿Qué afirmación es correcta en cuanto a las variables de usuario y variables\n    predefinidas?", "Las variables predefinidas suelen corresponder con el nombre de los campos del origen\n    de datos vinculado al informe.", "Las variables de usuario no pueden corresponder con el nombre de los campos del\n    origen de datos vinculado al informe.", "Las variables predefinidas aparecen por defecto en la herramienta, por lo que siempre\n    van a estar presentes y modelan elementos habituales en la generación de cualquier\n    informe.", "Las variables de usuario aparecen por defecto en la herramienta, por lo que siempre van\n    a estar presentes y modelan elementos habituales en la generación de cualquier informe.", "3");
           
           /*061*/      tipo_test("¿Qué pauta para la creación de una interfaz iOS es correcta?", "Adaptación al contenido.", "Claridad e iconos precisos.", "Correcta distribución de los componentes.", "Todas las respuestas son correctas.", "4");
           /*062*/      tipo_test("Las pruebas de capacidad:", "Se utilizan para la evaluación de la capacidad de procesamiento del software ante la\n    llegada de una cantidad grande de datos.", "Se utilizan para la evaluación de la capacidad de recuperación del software ante una\n    sobrecarga de datos.", "Se utilizan para la evaluación del tiempo de respuesta y la velocidad de procesamiento\n    del software.", "Se utilizan para la evaluación del software y su comportamiento ante un aumento de\n    peticiones, es decir, ante un incremento de la carga de trabajo.", "4");
           /*063*/      //tipo_test("", "", "", "", "", "");
           /*064*/      tipo_test("¿Qué es una tabla de contenido en un sistema de ayuda?", "Permite reflejar la estructura de un documento de ayuda.", "Permite reflejar el contenido de un documento de ayuda.", "Se encuentra esquematizada en varios niveles.", "Todas las respuestas son correctas.", "4");
           /*065*/      tipo_test("La documentación técnica:", "Sirve para documentar las pruebas realizadas sobre un programa determinado.", "Se trata de los informes resultantes de aplicar las pruebas sobre los programas.", "Es la documentación en la que especifican los escenarios de prueba\n    y se detallan los procedimientos de las mismas.", "Son las guías, hojas de especificaciones, manuales, etc.", "4");
           /*066*/      //tipo_test("", "", "", "", "", "");
           /*067*/      tipo_test("Se trata de un contenedor vacío utilizado para colocar los destinos hacia los que\n        apunta el gráfico de navegación. Este elemento permite que los destinos vayan\n        modificándose según el usuario navegada a través de la aplicación:", "Gráfico de navegación.", "Nav_version.", "NavController.", "NavHost.", "4");
           /*068*/      tipo_test("¿A qué fichero accedemos para poder ver la pantalla de diseño y el código asociado?", "manifest.py", "activity_main.xml", "default_main_registry.java", "Ninguna respuesta es correcta.", "2");
           /*069*/      //tipo_test("", "", "", "", "", "");
           /*070*/      tipo_test("¿Qué tipo de operaciones se utilizan sobre los valores contenidos en una columna?", "Recuentos y totales.", "Selecciones.", "Anulaciones.", "Ninguna de las anteriores.", "1");
           
           /*071*/      tipo_test("¿Qué delimitadores se utilizan para comentar varias líneas o fragmentos de código?", "/**/", "*//*", "//", "Ninguna respuesta es correcta.", "1");
           /*072*/      tipo_test("Las pruebas de rendimiento:", "Se utilizan para la evaluación de la capacidad de procesamiento del software ante la\n    llegada de una cantidad grande de datos.", "Se utilizan para la evaluación de la capacidad de recuperación del software ante una\n    sobrecarga de datos.", "Se utilizan para la evaluación del tiempo de respuesta y la velocidad de procesamiento\n    del software.", "Se utilizan para la evaluación del software y su comportamiento ante un aumento de\n    peticiones, es decir, ante un incremento de la carga de trabajo.", "3");
           /*073*/      //tipo_test("", "", "", "", "", "");
           /*074*/      tipo_test("¿Qué partes componen la estructura general de cualquier fichero de ayuda?", "Solamente una parte, el mapa de fichero.", "Solamente una parte, la vista de información.", "Dos partes, mapa de fichero y la vista de información.", "No contiene distintas partes.", "3");
           /*075*/      tipo_test("¿Qué tipo de manual o guía contiene la información necesaria para poner en uso\n        una aplicación?", "El manual de usuario.", "El manual de explotación.", "La guía rápida.", "La guía de referencia.", "2");
           /*076*/      //tipo_test("", "", "", "", "", "");
           /*077*/      tipo_test("¿De qué tipo es el elemento que representa cada una de las pantallas colocadas en el\n        editor?", "enterAnim.", "Fragment.", "Action.", "Destination.", "2");
           /*078*/      tipo_test("¿Qué versión de un producto es la primera versión y evaluada por expertos?", "Versión Alfa.", "Versión Beta.", "Versión Gamma.", "Versión definitiva.", "1");
           /*079*/      //tipo_test("", "", "", "", "", "");
           /*080*/      tipo_test("¿Qué variable devuelve el número de registros mostrados en cada página?", "PAGE_NUMBER.", "COLUMN_NUMBER.", "REPORT_COUNT.", "PAGE_COUNT.", "4");
           
           /*081*/      tipo_test("¿Qué delimitadores se utilizan para comentar una sola línea de código?", "/**/", "*//*", "//", "Ninguna respuesta es correcta.", "3");
           /*082*/      tipo_test("Los test de usuario se basan en pruebas que observan la forma de interacción de los\n        usuarios con el producto objeto del test según el:", "Diseño Directo en la Herramienta (DDH).", "Diseño Centrado en la Yuxtaposición (DCU).", "Diseño Centrado en el Usuario (DCU).", "Diseño Centrado en el Experto (DCE).", "3");
           /*083*/      //tipo_test("", "", "", "", "", "");
           /*084*/      tipo_test("¿Qué parámetros pueden ser creados desde cero?", "Integrados.", "De usuario.", "Solamente existe un tipo de parámetro, sin distinción.", "Ninguna es correcta.", "2");
           /*085*/      tipo_test("JavaHelp requiere del uso de diferentes ficheros y de diferentes tipos de estos para el\n        diseño de cada una de las partes que forman la ayuda final, como el fichero Helpset que:", "Incluye la distribución del sistema de ayuda.", "Asocia elementos del fichero HTML con un identificador.", "Contiene la información necesaria para que el sistema de ayuda se ejecute.", "Contiene la información de ayuda como tal, debiéndose realizar uno por cada tema.", "3");
           /*086*/      //tipo_test("", "", "", "", "", "");
           /*087*/      tipo_test("¿Cuál de los siguientes valores para el atributo showAsAction permite indicar que si\n        hay sitio en la barra de la aplicación se coloca el icono del botón y si no lo hay se\n        ubica en el menú ampliado (los 3 puntos verticales)?", "never.", "little.", "asAction.", "ifRoom.", "4");
           /*088*/      tipo_test("¿Qué versión de un producto es casi definitiva y probada por los clientes?", "Versión Alfa.", "Versión Beta.", "Versión Gamma.", "Versión definitiva.", "2");
           /*089*/      //tipo_test("", "", "", "", "", "");
           /*090*/      tipo_test("¿Qué variable devuelve el número de columnas del informe?", "PAGE_NUMBER.", "COLUMN_NUMBER.", "REPORT_COUNT.", "PAGE_COUNT.", "2");
           
           /*091*/      tipo_test("¿Cómo podemos comenzar a trabajar con las librerías de UI de Swift?", "import Swift UI.", "xcode export UI.", "import javax.swing.", "import xcode.", "1");
           /*092*/      tipo_test("La versión alfa de un producto:", "Consiste en la primera versión de la aplicación.", "Consiste en la última versión de la aplicación.", "Consiste en la versión casi definitiva de la aplicación.", "Se testea por los usuarios de tipo beta tester.", "1");
           /*093*/      //tipo_test("", "", "", "", "", "");
           /*094*/      tipo_test("¿Qué parámetros son los disponibles de forma predeterminada?", "Integrados.", "De usuario.", "Solamente existe un tipo de parámetros, sin distinción.", "Ninguna respuesta es correcta.", "1");
           /*095*/      tipo_test("La clase HelpBroker permite visualizar el contenido de la ayuda desde la aplicación,\n        ¿Cuál de los siguientes no es uno de sus principales métodos?", "enableHelpKey.", "enableHelpOnButton.", "enableHelp.", "findHelpSet.", "4");
           /*096*/      //tipo_test("", "", "", "", "", "");
           /*097*/      tipo_test("¿Qué tipo de animación está asociada a la entrada en una pantalla a través de una\n        acción emergente?", "enterAnim.", "popEnterAnim.", "exitAnim.", "popExistAnim.", "2");
           /*098*/      tipo_test("¿Qué tipo de prueba evalúa la velocidad de procesamiento del software?", "Prueba de Seguridad.", "Prueba de Estrés.", "Prueba de Volumen.", "Prueba de Rendimiento.", "4");
           /*099*/      //tipo_test("", "", "", "", "", "");
           /*100*/      tipo_test("¿Qué tipo de objeto java devuelve la operación SUM?", "java.lang.Number.", "java.lang.Double.", "java.lang.Boolean.", "java.lang.Integer.", "1");
           
           /*101*/      tipo_test("¿Qué entorno de desarrollo utilizamos para desarrollo de proyectos para Apple?", "Eclipse.", "Netbeans.", "Xcode.", "Notepad++.", "3");
           /*102*/      tipo_test("Por defecto, cuando se accede por primera vez a un proyecto creado con Android\n        Studio, el fichero que se muestra al desarrollador es el llamado:", "InitProyect.kt.", "InitActivity.kt.", "MainProyect.kt.", "MainActivity.kt.", "4");
           /*103*/      //tipo_test("", "", "", "", "", "");
           /*104*/      tipo_test("¿Podemos enviar parámetros al informe creado?", "Los parámetros permiten distintos informes con el mismo fichero de diseño.", "Los parámetros no están permitidos en los informes.", "Se permiten los parámetros pero solamente son de un tipo.", "Ninguna respuesta es correcta.", "1");
           /*105*/      tipo_test("Los sistemas de gestión de paquetes permiten automatizar los procesos relativos a:", "La instalación de paquetes software", "La configuración de paquetes software.", "El borrado de los paquetes software.", "Todas las anteriores son correctas.", "4");
           /*106*/      //tipo_test("", "", "", "", "", "");
           /*107*/      tipo_test("Para comentar el Código se pueden utilizar delimitadores para líneas o fragmento\n        de código del tipo:", "// comentario", "/* comentario */ ", "*/ comentario /*", "//* comentario *//", "2");
           /*108*/      tipo_test("Clasificación, ¿qué opción identifica un tipo de prueba?", "Pruebas unitarias.", "Pruebas de integración.", "Pruebas de seguridad.", "Todas las respuestas son correctas.", "4");
           /*109*/      //tipo_test("", "", "", "", "", "");
           /*110*/      tipo_test("Para la configuración de los parámetros de la base de datos en MySQL en primer lugar\n        se debe seleccionar el JDBC Driver:", "com.myddbb.jdbc.Driver.", "com.mysql.jdbc.Disc.", "com.myjdbc.bbdd.Disc.", "com.mysql.jdbc.Driver.", "4");
           
           /*111*/      tipo_test("¿Qué representa el código de la imagen?\n        <fragment            \n            android:id=\"@+id/ThirdFragment\"\n            android:name=\"com.example.myapplication.SecondFragment\"\n        </fragment>", "Indica un nuevo icono sobre la pantalla.", "Indica el nombre de una nueva pantalla.", "Indica la creación de una nueva acción.", "Ninguna respuesta es correcta.", "2");
           /*112*/      tipo_test("¿Desde qué fichero será necesario acceder para que esté disponible la pantalla de\n        diseño y el código asociado a la creación de cada nuevo componente?", "Main_activity.xml.", "Activity_proyect.xml.", "Activity_main.xml.", "Content_main.xml.", "3");
           /*113*/      //tipo_test("", "", "", "", "", "");
           /*114*/      tipo_test("¿Podemos actuar sobre los valores insertados en un informe?", "Solo se restringe al contenido de base de datos.", "No podemos modificar los datos al presentarlos.", "Usando el editor de expresiones podemos personalizar los datos.", "Ninguna respuesta es correcta.", "3");
           /*115*/      tipo_test("¿Cuál de los siguientes tipos de paquetes pueden ser instalados directamente sin\n        necesidad de ser extraídos previamente?", "RPM.", "TGZ.", "deb.", "TAR.", "3");
           /*116*/      //tipo_test("", "", "", "", "", "");
           /*117*/      tipo_test("Indica cuál es el sistema operativo de los dispositivos móviles de Apple:", "iOS.", "Android.", "Mac OS.", "Firefox OS.", "1");
           /*118*/      tipo_test("¿Qué prueba evalúa la aplicación desde un punto de vista externo?", "Pruebas de caja blanca.", "Pruebas de caja negra.", "Pruebas de caja marrón.", "Ninguna respuesta es correcta.", "2");
           /*119*/      //tipo_test("", "", "", "", "", "");
           /*120*/      tipo_test("En el último paso de la configuración del Driver Classpath se seleccionará el fichero:", ".xml", ".zip", ".jar", ".dmg", "3");
           
           /*121*/      tipo_test("Android Studio, ¿se puede añadir nuevas pantallas utilizando código XML?", "Insertando código XML como <fragment ...>", "Insertando código XML como <Android:screen ...>", "Solamente podemos hacer usando clases.", "Ninguna respuesta es correcta.", "1");
           /*122*/      tipo_test("¿Cuál de las siguientes no corresponde con una de las posibles formas de visualizar el\n        entorno de desarrollo Android Studio?", "Zoom.", "Code.", "Design.", "Split.", "1");
           /*123*/      //tipo_test("", "", "", "", "", "");
           /*124*/      tipo_test("Informes y subinformes, ¿cuál tiene encabezado y pie de página?", "Ambos, informes y subinformes.", "Solo los informes.", "Solo los subinformes.", "Ninguna respuesta es correcta.", "2");
           /*125*/      tipo_test("¿Qué diferencia existen entre los formatos para la creación de paquetes TAR y TGZ?", "TAR es un formato utilizado para la creación de paquetes sin compresión.", "TGZ es un formato utilizado para la creación de paquetes sin compresión.", "TAR es un formato utilizado para la creación de paquetes con compresión a través de\n    gunzip.", "TGZ es un formato utilizado para la creación de paquetes con compresión a través de\n    Redhat Package Manager.", "1");
           /*126*/      //tipo_test("", "", "", "", "", "");
           /*127*/      tipo_test("La herramienta que se utiliza para el desarrollo en el sistema operativo de dispositivos\n        móviles de Apple es:", "iApp.", "iCODE.", "Xmode.", "Xcode.", "4");
           /*128*/      tipo_test("¿Qué prueba evalúa el código interno del software?", "Pruebas de caja blanca.", "Pruebas de caja negra.", "Pruebas de caja marrón.", "Ninguna respuesta es correcta.", "1");
           /*129*/      //tipo_test("", "", "", "", "", "");
           /*130*/      tipo_test("Para la construcción de una instrucción de filtrado es imprescindible el uso de la\n        palabra:", "WHERE.", "WHEN.", "WHY.", "WHAT.", "1");
           
           /*131*/      tipo_test("¿Qué propiedad muestra una animación asociada a la entrada en una pantalla?", "app:popExitAnim.", "app:popEnterAnim.", "app:exitAnim.", "app:enterAnim.", "4");
           /*132*/      tipo_test("¿Con qué forma de visualización del entorno Android Studio se obtiene la división de\n        la zona de interacción en explorador, zona de desarrollo y zona de diseño?", "Zoom.", "Code.", "Design.", "Split.", "4");
           /*133*/      //tipo_test("", "", "", "", "", "");
           /*134*/      tipo_test("Informes y subinformes, ¿cuál puede incluir subinformes?", "Solamente los informes pueden incluir subinformes.", "Solamente los subinformes pueden incluir otros subinformes.", "Informes y subinformes pueden incluir a otros subinformes.", "Ninguna es correcta.", "1");
           /*135*/      tipo_test("¿Qué paquetes podemos encontrar para el empaquetado de aplicaciones\n        en Windows?", "MSI y AppX.", "MSI y DEB.", "DEB y AppX.", "TGZ y TAR.", "1");
           /*136*/      //tipo_test("", "", "", "", "", "");
           /*137*/      tipo_test("El lenguaje de programación utilizado para el desarrollo de las aplicaciones en iOS es:", "Swift.", "Java.", "Kotlin.", "JavaScript.", "1");
           /*138*/      tipo_test("¿Qué nos permite el uso de la herramienta Launch4j?", "Realización de pruebas de carga.", "Creación de un exe a través de un paquete JAR.", "Creación de ficheros de log para una aplicación.", "Ninguna respuesta es correcta.", "2");
           /*139*/      //tipo_test("", "", "", "", "", "");
           /*140*/      tipo_test("Tras la creación de informe y la conexión de este con las tablas contenedoras de los\n        datos, será posible utilizar estos campos para:", "Su importación en un informe.", "Su exportación en un informe.", "Su exportación en una base de datos.", "Su importación en una base de datos.", "1");
           
           /*141*/      tipo_test("¿Qué propiedad muestra una animación asociada a la salida de la pantalla a través de\n        una acción emergente?", "app:popExitAnim.", "app:popEnterAnim.", "app:exitAnim.", "app:enterAnim.", "1");
           /*142*/      tipo_test("En el desarrollo de interfaces Android el elemento layout permite definir la\n        característica:", "Posición de los elementos.", "Dimensión de los elementos.", "Distribución de los elementos.", "Todas son correctas.", "4");
           /*143*/      //tipo_test("", "", "", "", "", "");
           /*144*/      tipo_test("¿Existen diferencias entre informes y subinformes?", "Tanto los informes como los subinformes existen por sí solos.", "Son exactamente iguales.", "Presentan similitudes pero existen diferencias claras.", "No existe la posibilidad de crear subinformes.", "3");
           /*145*/      tipo_test("¿Qué tipo de empaquetado suele realizarse de las aplicaciones en Java?", ".net", ".java", ".bean", ".jar", "4");
           /*146*/      //tipo_test("", "", "", "", "", "");
           /*147*/      tipo_test("En la aplicación Xcode crear un 'playground' permite:", "Abrir un proyecto anterior.", "Implementar aplicaciones.", "Implementar ciertos bloques de código.", "Crear un nuevo proyecto.", "3");
           /*148*/      tipo_test("¿Cuál es el formato habitual para el empaquetado de aplicaciones en Java?", "Ficheros JAR.", "Ficheros XML.", "Ficheros *.java.", "Ninguna respuesta es correcta.", "1");
           /*149*/      //tipo_test("", "", "", "", "", "");
           /*150*/      tipo_test("Para el diseño de un informe se debe diferenciar en los textos a estáticos (Static Text)\n        y los campos de texto (Text Field). Los que se utilizan como si fueran etiquetas y son\n        las habituales para la creación de los títulos son:", "Text Field.", "Note.", "Break.", "Static Text.", "4");
           
           /*151*/      tipo_test("¿Podemos dotar de cierta animación a la transición entre pantallas?", "Siempre se programa en la clase.", "Siempre se programa usando XML.", "Utilizando propiedades como app:enterAnim.", "No es posible programar esto.", "3");
           /*152*/      tipo_test("¿Qué grupo de elementos son de tipo botón o con un comportamiento similar\n        (checkbox, togglebutton, radiobutton, ...)?", "Common.", "Containers.", "Layouts.", "Buttons.", "4");
           /*153*/      //tipo_test("", "", "", "", "", "");
           /*154*/      tipo_test("¿Qué variable predefinida devuelve el número de columnas del informe?", "PAGE_NUMBER.", "REPORT_COUNT.", "COLUMN_NUMBER.", "Ninguna es correcta.", "3");
           /*155*/      tipo_test("¿Cuál de los siguientes es un instalador muy utilizado?", "InstallBuilder.", "Windows Installer.", "MSI Studio.", "Todas son correctas.", "4");
           /*156*/      //tipo_test("", "", "", "", "", "");
           /*157*/      tipo_test("Indica cuál de los siguientes sistemas operativos no se puede utilizar en la aplicación\n        Xcode:", "iOS.", "watchOS.", "iTV.", "macOS.", "3");
           /*158*/      tipo_test("¿Existe diferencia entre DEB y RPM?", "DEB es usado en distribuciones basadas en Debian.", "RPM es usado en distribuciones Debian.", "DEB se genera con la herramienta Redhat Package Manager.", "No hay ninguna diferencia.", "1");
           /*159*/      //tipo_test("", "", "", "", "", "");
           /*160*/      tipo_test("Además de la creación de informes relativos al desarrollo de aplicaciones, para\n        mejorar la legibilidad de la información y garantizar un estructura más óptima,\n        podemos realizar también:", "Subinformes.", "Apartados.", "Índices.", "Bases de datos.", "1");
           
           /*161*/      tipo_test("¿Qué permite el componente Navigation de Android?", "Permite implementar cualquier diseño de navegación.", "Se utiliza para diseñar la secuencia de pasos entre pantallas.", "La navegación se puede realizar con un alto grado de personalización.", "Todas las respuestas son correctas.", "4");
           /*162*/      tipo_test("¿Qué elementos extras permiten personalizar la interfaz de desarrollo\n        (calendarios, barras de progreso ...)?", "Common.", "Containers.", "Layouts.", "Widgets.", "4");
           /*163*/      //tipo_test("", "", "", "", "", "");
           /*164*/      tipo_test("¿Cómo se denominan a las variables que aparecen por defecto en la herramienta?", "Variables predefinidas.", "Variables de usuario.", "Variables internas.", "Ninguna es correcta.", "1");
           /*165*/      tipo_test("Este instalador de Windows permite realizar la instalación de forma predefinida:", "AppX.", "DEB.", "EXE.", "MSI.", "4");
           /*166*/      //tipo_test("", "", "", "", "", "");
           /*167*/      tipo_test("¿Cuál es la nueva interfaz de usuario utilizada para iOS?", "Storyboard.", "SwiftUI.", "Objective-C.", "Swift.", "2");
           /*168*/      tipo_test("¿Existe diferencia entre los ficheros TGZ y TAR?", "TGZ son paquetes sin compresión.", "TAR está comprimido a través de GUNZIP.", "TAR son paquetes sin compresión.", "No hay ninguna diferencia.", "3");
           /*169*/      //tipo_test("", "", "", "", "", "");
           /*170*/      tipo_test("La principal diferencia entre los informes y los subinformes son:", "Los subinformes pueden contener más subinformes, no tienen ni encabezados ni pie de\n    página y no tienen existencia por sí solos.", "Los informes pueden contener más subinformes, no tienen ni encabezados ni pie de\n    página y no tienen existencia por sí solos.", "Los informes no pueden contener más subinformes, tienen encabezados y pie de\n    página y no tienen existencia por sí solos.", "Los subinformes no pueden contener más subinformes, no tienen ni encabezados ni pie\n    de página y no tienen existencia por sí solos.", "4");
           
           /*171*/      tipo_test("¿Qué escuchador debemos implementar para detectar cuando se hace clic?", "OnClickListener.", "OnFocusChangeListener.", "OnExitListener.", "Ninguna respuesta es correcta.", "1");
           /*172*/      tipo_test("¿Qué elemento es utilizado para modelar los menús desplegables en una aplicación Android?", "ToggleButton.", "Spinner.", "Checkbox.", "TextField.", "2");
           /*173*/      //tipo_test("", "", "", "", "", "");
           /*174*/      tipo_test("¿Cómo se denomina a las variables que normalmente corresponde con los campos del\n        origen de datos?", "Variables predefinidas.", "Variables de usuario.", "Variables internas.", "Ninguna es correcta.", "2");
           /*175*/      tipo_test("Para la distribución de aplicaciones software puede realizarse desde un servidor web.\n        Una de las herramientas que permite la descarga e instalación de paquetes alojados\n        en un servidor web es:", "AptWeb.", "AptUrl.", "WebDeb.", "UrlExe.", "2");
           /*176*/      //tipo_test("", "", "", "", "", "");
           /*177*/      tipo_test("La función Navigator es una de las más importantes de la aplicación Xcode y se\n        encuentra situada en la:", "Zona inferior.", "Zona derecha.", "Zona de desarrollo.", "Zona izquierda.", "4");
           /*178*/      tipo_test("¿Cuál es el formato habitual para empaquetar y distribuir aplicaciones en Linux?", "DEB.", "TAR.", "TGZ.", "Todas las respuestas son correctas.", "4");
           /*179*/      //tipo_test("", "", "", "", "", "");
           /*180*/      tipo_test("Para incluir un subinforme se coloca en el visor de diseño desde la paleta de\n        elementos el elemento:", "Generic.", "Frame.", "Subreport.", "Barcode.", "3");
           
           /*181*/      tipo_test("¿Qué elemento permite mostrar un mensaje en forma de caja de texto o similar en una\n        aplicación Android?", "Button.", "Checkbox.", "TextView.", "Spinner.", "3");
           /*182*/      tipo_test("¿Cuál de los siguientes elementos permite añadir un conmutador entre estados en el\n        desarrollo de una aplicación?", "CheckBox.", "Spinner.", "ToggleButton.", "Ninguno de los anteriores.", "3");
           /*183*/      //tipo_test("", "", "", "", "", "");
           /*184*/      tipo_test("¿Qué formatos de salida están permitidos para un informe?", "Se pueden adaptar muchos formatos de salida.", "Solo en formato de salida en PDF para su portabilidad.", "Formato en fichero XML para su intercambio.", "Formato en fichero CSV para su integración con office.", "1");
           /*185*/      tipo_test("¿Qué herramienta podemos utilizar para crear un tipo EXE a través de un paquete JAR?", "EnableSplash.", "AptUrl.", "Launch4j.", "Dpkg.", "3");
           /*186*/      //tipo_test("", "", "", "", "", "");
           /*187*/      tipo_test("El código que será necesario implementar para importar la librería SwiftUI es:", "import Swift.", "import SwiftUI.", "import UI.", "import View.", "2");
           /*188*/      tipo_test("¿Cuáles son componentes principales en la distribución de las aplicaciones?", "Ficheros ejecutables.", "Carpetas de elementos multimedia.", "La biblioteca y librerías.", "Todas las respuestas son correctas.", "4");
           /*189*/      //tipo_test("", "", "", "", "", "");
           /*190*/      tipo_test("Para personalizar la cadena de texto con la que serán incluidos los datos en un\n        informe se utilizará:", "El editor de expresiones.", "El editor de variables.", "El emulador de sintaxis.", "El gestor de código.", "1");
           
           /*191*/      tipo_test("¿Qué elemento se usan para modelar desplegables en una aplicación Android?", "Button.", "TextField.", "TextView.", "Spinner.", "4");
           /*192*/      tipo_test("¿Cuál de los siguientes elementos determina el valor de la altura del elemento o\n        componente insertado en la interfaz de la aplicación?", "layout_width.", "layout_height", "layout_margin.", "layout_gravity.", "2");
           /*193*/      //tipo_test("", "", "", "", "", "");
           /*194*/      tipo_test("¿Qué origen de datos de entrada es válido para la creación de informes?", "Base de datos.", "Ficheros XML.", "Hojas de cálculo.", "Todas las respuestas son correctas.", "4");
           /*195*/      tipo_test("¿Cuál de los siguientes organismos emite certificados de firma digital?", "FNMT.", "TNN.", "TNT.", "FETA.", "1");
           /*196*/      //tipo_test("", "", "", "", "", "");
           /*197*/      tipo_test("Para crear variables en el lenguaje Swift se utiliza:", "v.", "save.", "new.", "var.", "4");
           /*198*/      tipo_test("¿Qué fichero de JavaHelp contiene la información de ayuda como tal?", "XML.", "JHM.", "HTML.", "Ninguna respuesta es correcta.", "3");
           /*199*/      //tipo_test("", "", "", "", "", "");
           /*200*/      tipo_test("El parámetro que permite mostrar el nombre de la conexión es:", "REPORT_CONTEXT.", "REPORT_PARAMETERS_MAP.", "REPORT_CONNECTION.", "REPORT_LOCALE.", "3");
           
    }    
}